### ISSUE TITLE
leastes Yii 2 version

### ISSUE THREAD

**Issue by EngRajabi** [nbphpcouncil/nb-yii2-plugin#11]
linke site yii
http://www.yiiframework.com/doc-2.0/guide-start-installation.html
install project with composer :
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
this always leastes version
bute note command plugin create project

**Comment by junichi11** [comment]
> bute note command plugin create project

What does this mean? What do you want to do?

If you want to create a new yii2 project in NetBeans IDE, please try to check the following:
`New Project > PHP > Yii2 Framework Application`.

**Comment by EngRajabi** [comment]
change composer command to 
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
get leates version yii 2

**Comment by junichi11** [comment]
Plugin runs `composer create-project --prefer-dist yiisoft/yii2-app-basic` 

I'm not sure yet. Please write expected result and actual result.

**Comment by EngRajabi** [comment]
no , so sorry
I made a mistake

**Comment by junichi11** [comment]
No problem :)
