### ISSUE TITLE
Yii 2 version

### ISSUE THREAD

**Issue by EngRajabi** [nbphpcouncil/nb-yii2-plugin#12]
change composer command to
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
always get leates version yii 2
bute now get with version change command composer to always leates version
composer create-project --prefer-dist yiisoft/yii2-app-basic basic

**Comment by junichi11** [comment]
Why do you create a new issue? What is the difference between #11 and this?

**Comment by EngRajabi** [comment]
no , so sorry
I made a mistake
