### ISSUE TITLE
Installing plugin nb-yii2-plugin (NetBeans 8.0.2)

### ISSUE THREAD

**Issue by PeterJason** [nbphpcouncil/nb-yii2-plugin#15]
Hi

I'm trying install that plugin but i can't.
How can i fix it?
http://prntscr.com/a8p6x2
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Thanks

**Comment by junichi11** [comment]
Please look at "Requirements" for nbms. In your version, please try using the following: 
https://github.com/nbphpcouncil/nb-yii2-plugin/releases/tag/v0.0.3
