### ISSUE TITLE
HI. I want to know about plugin fate. Yii2 stable(Oct 12, 2014) and the latest version is 2.0.1(dec 7, 2014)

### ISSUE THREAD

**Issue by keltstr** [nbphpcouncil/nb-yii2-plugin#2]
HI. I want to know about plugin fate.
 Yii2 stable release 2.0.0(Oct 12, 2014) 
and the latest version is 2.0.1(Dec 7, 2014)
Thanks for great deal !

**Comment by junichi11** [comment]
> HI. I want to know about plugin fate.

What does this mean?

**Comment by keltstr** [comment]
is it work ?

**Comment by junichi11** [comment]
Probably, it works (There are just a few features).
But, please wait a while... e.g. have a look at #4 

BTW, I hope that you set a proper title when you submit an issue. Title is not detailed description.  

Thanks.

**Comment by saidbakr** [comment]
The second release works on NetBeans 8.0.2.
