### ISSUE TITLE
The readme file missing information about enabling.

### ISSUE THREAD

**Issue by saidbakr** [nbphpcouncil/nb-yii2-plugin#4]
The release # 2 was installed successfully on NetBeans 8.0.2. However, when Enabling yii2 for the project I found some expression, that I think, it should be defined or explained in the readme, they are:

 - Base path of application
 - Path aliases file path

**Comment by junichi11** [comment]
I'll add that later. NOTE: This plugin has not been finished. I can't promise do it soon because I have no time to develop this plugin at the moment.

**Comment by ahmadazizi** [comment]
I don't know how to install or enable this plugin. There is no .nbm file to install or any instructions in readme.

**Comment by saidbakr** [comment]
@ahmadazizi Simply, go the package [home page](https://github.com/nbphpcouncil/nb-yii2-plugin) and then click on the link titled [**releases** ](https://github.com/nbphpcouncil/nb-yii2-plugin/releases) then download the latest version. (now it is 0.0.2 dev). then install it from your Netbeans plugins tool.

**Comment by ahmadazizi** [comment]
Thanks @saidbakr 
Could find the release files there, I'm kind of new in github ;)

**Comment by saidbakr** [comment]
@ahmadazizi Go to [this link](https://github.com/nbphpcouncil/nb-yii2-plugin/releases) and click on the first green button to download the nbm. Be sure that your Netbeans is 8.0.2

**Comment by junichi11** [comment]
> Base path of application

Have a look at http://www.yiiframework.com/doc-2.0/guide-structure-applications.html#basepath

> Path aliases file path

User may change the default directory structure. (e.g. may use `mycontrollers` directory instead of  `controllers` directory)

Path aliases file support for it. It's a json file like the following: https://gist.github.com/junichi11/9db666005afc0fb20c16

I'll add it to README file later.

Thanks.

**Comment by junichi11** [comment]
Done.

Thanks.

**Comment by saidbakr** [comment]
There is a problem in the Advanced application template, indeed, it is two applications in one. For example, creating new project in netbeans I may have to set `C:\xampp-2\htdocs\yii2build` as project folder which automatically will be set as Base Path location in the Yii2 plugin, so when I try to add relative Base Path Of Application to be `frontend\web` The Base Path Location of the plugin will be suffixed with it. So I think that in Advanced Application two or more Base Path of Application fields should be found.

**Comment by junichi11** [comment]
Advanced application is not supported yet in this plugin.
