### ISSUE TITLE
latest yii 2

### ISSUE THREAD

**Issue by EngRajabi** [nbphpcouncil/nb-yii2-plugin#8]
i using plugin and create project with netbeans bute now yii 2.0.2 bute netbeans create yii 2.0.0 project

**Comment by junichi11** [comment]
Fixed.

Could you try to use it ? 
https://github.com/nbphpcouncil/nb-yii2-plugin/releases/tag/v0.0.3 

Then please read the following:
https://github.com/nbphpcouncil/nb-yii2-plugin/blob/master/README.md#create-a-new-project-via-composer

Thanks.
